// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwR36ZLNkp1IxUEG-nnmYOGmipPxpLZ4s',
    appId: '1:368110045431:web:ec243c4838a7b20199ebf2',
    messagingSenderId: '368110045431',
    projectId: 'tdlist-yndx',
    authDomain: 'tdlist-yndx.firebaseapp.com',
    storageBucket: 'tdlist-yndx.appspot.com',
    measurementId: 'G-BK2HRCX42T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqVAwEj_cA5ndYYZgGXTG_4B-BjGMeEY',
    appId: '1:368110045431:android:41e98697884ad87a99ebf2',
    messagingSenderId: '368110045431',
    projectId: 'tdlist-yndx',
    storageBucket: 'tdlist-yndx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBToEr-4eh8OJbLFW4q4doh4n4VnVPtjy4',
    appId: '1:368110045431:ios:f89bd6200e1d7ddb99ebf2',
    messagingSenderId: '368110045431',
    projectId: 'tdlist-yndx',
    storageBucket: 'tdlist-yndx.appspot.com',
    iosClientId:
        '368110045431-lh205tci4domuiesl017uthb3qtv2msk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdlist',
  );
}
